# Generated by Django 4.1.5 on 2023-01-22 16:26

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome Completo', max_length=50)),
                ('cpf', cpf_field.models.CPFField(help_text='000.000.000-00', max_length=14, unique=True, verbose_name='cpf')),
                ('telefone', models.CharField(help_text='(00) 0 0000-0000', max_length=16)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], help_text='Sexo', max_length=1)),
                ('cep', models.CharField(help_text='01001-000', max_length=9)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], help_text='RS / SC', max_length=2)),
                ('cidade', models.CharField(help_text='Camaquã/ Pelotas', max_length=150)),
                ('logradouro', models.CharField(help_text='Casa / Hotel', max_length=50)),
                ('data_cadastrado', models.DateField(auto_now_add=True)),
                ('data_atualizado', models.DateField(auto_now=True)),
            ],
        ),
    ]
